package com.kss.kssmarketv10.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENTES".
 */
public class Clientes {

    private long id;
    /** Not-null value. */
    private String CI;
    /** Not-null value. */
    private String Nombres;
    private String Categorias;
    private String Pasaporte;
    private String telefono;
    private String telefono_movil;
    /** Not-null value. */
    private String direccion;
    private String Apellidos;
    /** Not-null value. */
    private String email;
    private Boolean esActivo;
    private Boolean esEmpresa;
    private Integer id_estado;
    private Integer id_municipio;
    private Integer id_nacionalidad;
    private Integer id_parroquia;
    private Integer id_profesion;
    private Integer codigoPostal;
    private Integer id_ciudad;
    private Integer id_tipoPago;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Clientes() {
    }

    public Clientes(long id) {
        this.id = id;
    }

    public Clientes(long id, String CI, String Nombres, String Categorias, String Pasaporte, String telefono, String telefono_movil, String direccion, String Apellidos, String email, Boolean esActivo, Boolean esEmpresa, Integer id_estado, Integer id_municipio, Integer id_nacionalidad, Integer id_parroquia, Integer id_profesion, Integer codigoPostal, Integer id_ciudad, Integer id_tipoPago) {
        this.id = id;
        this.CI = CI;
        this.Nombres = Nombres;
        this.Categorias = Categorias;
        this.Pasaporte = Pasaporte;
        this.telefono = telefono;
        this.telefono_movil = telefono_movil;
        this.direccion = direccion;
        this.Apellidos = Apellidos;
        this.email = email;
        this.esActivo = esActivo;
        this.esEmpresa = esEmpresa;
        this.id_estado = id_estado;
        this.id_municipio = id_municipio;
        this.id_nacionalidad = id_nacionalidad;
        this.id_parroquia = id_parroquia;
        this.id_profesion = id_profesion;
        this.codigoPostal = codigoPostal;
        this.id_ciudad = id_ciudad;
        this.id_tipoPago = id_tipoPago;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCI() {
        return CI;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCI(String CI) {
        this.CI = CI;
    }

    /** Not-null value. */
    public String getNombres() {
        return Nombres;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombres(String Nombres) {
        this.Nombres = Nombres;
    }

    public String getCategorias() {
        return Categorias;
    }

    public void setCategorias(String Categorias) {
        this.Categorias = Categorias;
    }

    public String getPasaporte() {
        return Pasaporte;
    }

    public void setPasaporte(String Pasaporte) {
        this.Pasaporte = Pasaporte;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getTelefono_movil() {
        return telefono_movil;
    }

    public void setTelefono_movil(String telefono_movil) {
        this.telefono_movil = telefono_movil;
    }

    /** Not-null value. */
    public String getDireccion() {
        return direccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getApellidos() {
        return Apellidos;
    }

    public void setApellidos(String Apellidos) {
        this.Apellidos = Apellidos;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getEsActivo() {
        return esActivo;
    }

    public void setEsActivo(Boolean esActivo) {
        this.esActivo = esActivo;
    }

    public Boolean getEsEmpresa() {
        return esEmpresa;
    }

    public void setEsEmpresa(Boolean esEmpresa) {
        this.esEmpresa = esEmpresa;
    }

    public Integer getId_estado() {
        return id_estado;
    }

    public void setId_estado(Integer id_estado) {
        this.id_estado = id_estado;
    }

    public Integer getId_municipio() {
        return id_municipio;
    }

    public void setId_municipio(Integer id_municipio) {
        this.id_municipio = id_municipio;
    }

    public Integer getId_nacionalidad() {
        return id_nacionalidad;
    }

    public void setId_nacionalidad(Integer id_nacionalidad) {
        this.id_nacionalidad = id_nacionalidad;
    }

    public Integer getId_parroquia() {
        return id_parroquia;
    }

    public void setId_parroquia(Integer id_parroquia) {
        this.id_parroquia = id_parroquia;
    }

    public Integer getId_profesion() {
        return id_profesion;
    }

    public void setId_profesion(Integer id_profesion) {
        this.id_profesion = id_profesion;
    }

    public Integer getCodigoPostal() {
        return codigoPostal;
    }

    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public Integer getId_ciudad() {
        return id_ciudad;
    }

    public void setId_ciudad(Integer id_ciudad) {
        this.id_ciudad = id_ciudad;
    }

    public Integer getId_tipoPago() {
        return id_tipoPago;
    }

    public void setId_tipoPago(Integer id_tipoPago) {
        this.id_tipoPago = id_tipoPago;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
