package com.kss.kssmarketv10.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EMPRESA".
 */
public class Empresa {

    private long id;
    private String Contacto;
    /** Not-null value. */
    private String direccion;
    /** Not-null value. */
    private String empresa;
    private String ImagenArchivo;
    private String nit;
    /** Not-null value. */
    private String rif;
    /** Not-null value. */
    private String telefonos;
    private String telefonosContacto;
    private Boolean esActivo;
    private Integer codigoPostal;
    private Integer Id_Ciudad;
    private Integer id_Estado;
    private Integer id_idioma;
    private Integer id_Municipio;
    private Integer id_Pais;
    private Integer Id_Parroquia;
    private Integer ID_tipoComercio;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Empresa() {
    }

    public Empresa(long id) {
        this.id = id;
    }

    public Empresa(long id, String Contacto, String direccion, String empresa, String ImagenArchivo, String nit, String rif, String telefonos, String telefonosContacto, Boolean esActivo, Integer codigoPostal, Integer Id_Ciudad, Integer id_Estado, Integer id_idioma, Integer id_Municipio, Integer id_Pais, Integer Id_Parroquia, Integer ID_tipoComercio) {
        this.id = id;
        this.Contacto = Contacto;
        this.direccion = direccion;
        this.empresa = empresa;
        this.ImagenArchivo = ImagenArchivo;
        this.nit = nit;
        this.rif = rif;
        this.telefonos = telefonos;
        this.telefonosContacto = telefonosContacto;
        this.esActivo = esActivo;
        this.codigoPostal = codigoPostal;
        this.Id_Ciudad = Id_Ciudad;
        this.id_Estado = id_Estado;
        this.id_idioma = id_idioma;
        this.id_Municipio = id_Municipio;
        this.id_Pais = id_Pais;
        this.Id_Parroquia = Id_Parroquia;
        this.ID_tipoComercio = ID_tipoComercio;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getContacto() {
        return Contacto;
    }

    public void setContacto(String Contacto) {
        this.Contacto = Contacto;
    }

    /** Not-null value. */
    public String getDireccion() {
        return direccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /** Not-null value. */
    public String getEmpresa() {
        return empresa;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    public String getImagenArchivo() {
        return ImagenArchivo;
    }

    public void setImagenArchivo(String ImagenArchivo) {
        this.ImagenArchivo = ImagenArchivo;
    }

    public String getNit() {
        return nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    /** Not-null value. */
    public String getRif() {
        return rif;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRif(String rif) {
        this.rif = rif;
    }

    /** Not-null value. */
    public String getTelefonos() {
        return telefonos;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }

    public String getTelefonosContacto() {
        return telefonosContacto;
    }

    public void setTelefonosContacto(String telefonosContacto) {
        this.telefonosContacto = telefonosContacto;
    }

    public Boolean getEsActivo() {
        return esActivo;
    }

    public void setEsActivo(Boolean esActivo) {
        this.esActivo = esActivo;
    }

    public Integer getCodigoPostal() {
        return codigoPostal;
    }

    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public Integer getId_Ciudad() {
        return Id_Ciudad;
    }

    public void setId_Ciudad(Integer Id_Ciudad) {
        this.Id_Ciudad = Id_Ciudad;
    }

    public Integer getId_Estado() {
        return id_Estado;
    }

    public void setId_Estado(Integer id_Estado) {
        this.id_Estado = id_Estado;
    }

    public Integer getId_idioma() {
        return id_idioma;
    }

    public void setId_idioma(Integer id_idioma) {
        this.id_idioma = id_idioma;
    }

    public Integer getId_Municipio() {
        return id_Municipio;
    }

    public void setId_Municipio(Integer id_Municipio) {
        this.id_Municipio = id_Municipio;
    }

    public Integer getId_Pais() {
        return id_Pais;
    }

    public void setId_Pais(Integer id_Pais) {
        this.id_Pais = id_Pais;
    }

    public Integer getId_Parroquia() {
        return Id_Parroquia;
    }

    public void setId_Parroquia(Integer Id_Parroquia) {
        this.Id_Parroquia = Id_Parroquia;
    }

    public Integer getID_tipoComercio() {
        return ID_tipoComercio;
    }

    public void setID_tipoComercio(Integer ID_tipoComercio) {
        this.ID_tipoComercio = ID_tipoComercio;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
