package com.kss.kssmarketv10.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LICENCIAS".
 */
public class Licencias {

    private long id;
    private String CodigoActivacion;
    private String CodigoRequerido;
    /** Not-null value. */
    private String CodigoSerial;
    private String MotherBoard_Serial;
    private String NombreEquipo;
    private String SistemaOperativo;
    private String SO_Version;
    private String hdd_Serial;
    private Boolean esActivo;
    private Boolean esOnline;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Licencias() {
    }

    public Licencias(long id) {
        this.id = id;
    }

    public Licencias(long id, String CodigoActivacion, String CodigoRequerido, String CodigoSerial, String MotherBoard_Serial, String NombreEquipo, String SistemaOperativo, String SO_Version, String hdd_Serial, Boolean esActivo, Boolean esOnline) {
        this.id = id;
        this.CodigoActivacion = CodigoActivacion;
        this.CodigoRequerido = CodigoRequerido;
        this.CodigoSerial = CodigoSerial;
        this.MotherBoard_Serial = MotherBoard_Serial;
        this.NombreEquipo = NombreEquipo;
        this.SistemaOperativo = SistemaOperativo;
        this.SO_Version = SO_Version;
        this.hdd_Serial = hdd_Serial;
        this.esActivo = esActivo;
        this.esOnline = esOnline;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCodigoActivacion() {
        return CodigoActivacion;
    }

    public void setCodigoActivacion(String CodigoActivacion) {
        this.CodigoActivacion = CodigoActivacion;
    }

    public String getCodigoRequerido() {
        return CodigoRequerido;
    }

    public void setCodigoRequerido(String CodigoRequerido) {
        this.CodigoRequerido = CodigoRequerido;
    }

    /** Not-null value. */
    public String getCodigoSerial() {
        return CodigoSerial;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigoSerial(String CodigoSerial) {
        this.CodigoSerial = CodigoSerial;
    }

    public String getMotherBoard_Serial() {
        return MotherBoard_Serial;
    }

    public void setMotherBoard_Serial(String MotherBoard_Serial) {
        this.MotherBoard_Serial = MotherBoard_Serial;
    }

    public String getNombreEquipo() {
        return NombreEquipo;
    }

    public void setNombreEquipo(String NombreEquipo) {
        this.NombreEquipo = NombreEquipo;
    }

    public String getSistemaOperativo() {
        return SistemaOperativo;
    }

    public void setSistemaOperativo(String SistemaOperativo) {
        this.SistemaOperativo = SistemaOperativo;
    }

    public String getSO_Version() {
        return SO_Version;
    }

    public void setSO_Version(String SO_Version) {
        this.SO_Version = SO_Version;
    }

    public String getHdd_Serial() {
        return hdd_Serial;
    }

    public void setHdd_Serial(String hdd_Serial) {
        this.hdd_Serial = hdd_Serial;
    }

    public Boolean getEsActivo() {
        return esActivo;
    }

    public void setEsActivo(Boolean esActivo) {
        this.esActivo = esActivo;
    }

    public Boolean getEsOnline() {
        return esOnline;
    }

    public void setEsOnline(Boolean esOnline) {
        this.esOnline = esOnline;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
