package com.kss.kssmarketv10.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCTOS".
 */
public class Productos {

    private long id;
    private String CodigoAdicional;
    /** Not-null value. */
    private String CodigoBarras;
    /** Not-null value. */
    private String CodigoInterno;
    /** Not-null value. */
    private String Producto;
    private String Producto_DescripcionLarga;
    private String Producto_LinkWeb;
    private Double cantidadUnidadVenta;
    private Double MargenGananciaPrecio1;
    private Double MargenGananciaPrecio2;
    private Double MargenGananciaPrecio3;
    private Double MedidaAlto;
    private Double MedidaAncho;
    private Double MedidaLargo;
    private Double MontoCostoPromedio;
    private double MontoPrecio1;
    private Double MontoPrecio2;
    private Double MontoPrecio3;
    private Double MontoUltimoCosto;
    private Boolean esActivo;
    private Boolean esCodigoAlterno;
    private Boolean esCompuesto;
    private Boolean esFavorito;
    private Boolean esGarantia;
    private Boolean esImportado;
    private Boolean esInventario;
    private Boolean esPideComentario;
    private Boolean esPidePeso;
    private Boolean esPidePrecio;
    private Boolean esPideTipoProducto;
    private Boolean esUsoInterno;
    private int id_familiaProducto;
    private Integer id_Marca;
    private Integer id_Impuesto;
    private Integer id_unidadMedida;
    private java.util.Date FechaCreacion;
    private java.util.Date FechaUltimaCompra;
    private java.util.Date FechaUltimaModificacion;
    private java.util.Date FechaUltimaVenta;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Productos() {
    }

    public Productos(long id) {
        this.id = id;
    }

    public Productos(long id, String CodigoAdicional, String CodigoBarras, String CodigoInterno, String Producto, String Producto_DescripcionLarga, String Producto_LinkWeb, Double cantidadUnidadVenta, Double MargenGananciaPrecio1, Double MargenGananciaPrecio2, Double MargenGananciaPrecio3, Double MedidaAlto, Double MedidaAncho, Double MedidaLargo, Double MontoCostoPromedio, double MontoPrecio1, Double MontoPrecio2, Double MontoPrecio3, Double MontoUltimoCosto, Boolean esActivo, Boolean esCodigoAlterno, Boolean esCompuesto, Boolean esFavorito, Boolean esGarantia, Boolean esImportado, Boolean esInventario, Boolean esPideComentario, Boolean esPidePeso, Boolean esPidePrecio, Boolean esPideTipoProducto, Boolean esUsoInterno, int id_familiaProducto, Integer id_Marca, Integer id_Impuesto, Integer id_unidadMedida, java.util.Date FechaCreacion, java.util.Date FechaUltimaCompra, java.util.Date FechaUltimaModificacion, java.util.Date FechaUltimaVenta) {
        this.id = id;
        this.CodigoAdicional = CodigoAdicional;
        this.CodigoBarras = CodigoBarras;
        this.CodigoInterno = CodigoInterno;
        this.Producto = Producto;
        this.Producto_DescripcionLarga = Producto_DescripcionLarga;
        this.Producto_LinkWeb = Producto_LinkWeb;
        this.cantidadUnidadVenta = cantidadUnidadVenta;
        this.MargenGananciaPrecio1 = MargenGananciaPrecio1;
        this.MargenGananciaPrecio2 = MargenGananciaPrecio2;
        this.MargenGananciaPrecio3 = MargenGananciaPrecio3;
        this.MedidaAlto = MedidaAlto;
        this.MedidaAncho = MedidaAncho;
        this.MedidaLargo = MedidaLargo;
        this.MontoCostoPromedio = MontoCostoPromedio;
        this.MontoPrecio1 = MontoPrecio1;
        this.MontoPrecio2 = MontoPrecio2;
        this.MontoPrecio3 = MontoPrecio3;
        this.MontoUltimoCosto = MontoUltimoCosto;
        this.esActivo = esActivo;
        this.esCodigoAlterno = esCodigoAlterno;
        this.esCompuesto = esCompuesto;
        this.esFavorito = esFavorito;
        this.esGarantia = esGarantia;
        this.esImportado = esImportado;
        this.esInventario = esInventario;
        this.esPideComentario = esPideComentario;
        this.esPidePeso = esPidePeso;
        this.esPidePrecio = esPidePrecio;
        this.esPideTipoProducto = esPideTipoProducto;
        this.esUsoInterno = esUsoInterno;
        this.id_familiaProducto = id_familiaProducto;
        this.id_Marca = id_Marca;
        this.id_Impuesto = id_Impuesto;
        this.id_unidadMedida = id_unidadMedida;
        this.FechaCreacion = FechaCreacion;
        this.FechaUltimaCompra = FechaUltimaCompra;
        this.FechaUltimaModificacion = FechaUltimaModificacion;
        this.FechaUltimaVenta = FechaUltimaVenta;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCodigoAdicional() {
        return CodigoAdicional;
    }

    public void setCodigoAdicional(String CodigoAdicional) {
        this.CodigoAdicional = CodigoAdicional;
    }

    /** Not-null value. */
    public String getCodigoBarras() {
        return CodigoBarras;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigoBarras(String CodigoBarras) {
        this.CodigoBarras = CodigoBarras;
    }

    /** Not-null value. */
    public String getCodigoInterno() {
        return CodigoInterno;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigoInterno(String CodigoInterno) {
        this.CodigoInterno = CodigoInterno;
    }

    /** Not-null value. */
    public String getProducto() {
        return Producto;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProducto(String Producto) {
        this.Producto = Producto;
    }

    public String getProducto_DescripcionLarga() {
        return Producto_DescripcionLarga;
    }

    public void setProducto_DescripcionLarga(String Producto_DescripcionLarga) {
        this.Producto_DescripcionLarga = Producto_DescripcionLarga;
    }

    public String getProducto_LinkWeb() {
        return Producto_LinkWeb;
    }

    public void setProducto_LinkWeb(String Producto_LinkWeb) {
        this.Producto_LinkWeb = Producto_LinkWeb;
    }

    public Double getCantidadUnidadVenta() {
        return cantidadUnidadVenta;
    }

    public void setCantidadUnidadVenta(Double cantidadUnidadVenta) {
        this.cantidadUnidadVenta = cantidadUnidadVenta;
    }

    public Double getMargenGananciaPrecio1() {
        return MargenGananciaPrecio1;
    }

    public void setMargenGananciaPrecio1(Double MargenGananciaPrecio1) {
        this.MargenGananciaPrecio1 = MargenGananciaPrecio1;
    }

    public Double getMargenGananciaPrecio2() {
        return MargenGananciaPrecio2;
    }

    public void setMargenGananciaPrecio2(Double MargenGananciaPrecio2) {
        this.MargenGananciaPrecio2 = MargenGananciaPrecio2;
    }

    public Double getMargenGananciaPrecio3() {
        return MargenGananciaPrecio3;
    }

    public void setMargenGananciaPrecio3(Double MargenGananciaPrecio3) {
        this.MargenGananciaPrecio3 = MargenGananciaPrecio3;
    }

    public Double getMedidaAlto() {
        return MedidaAlto;
    }

    public void setMedidaAlto(Double MedidaAlto) {
        this.MedidaAlto = MedidaAlto;
    }

    public Double getMedidaAncho() {
        return MedidaAncho;
    }

    public void setMedidaAncho(Double MedidaAncho) {
        this.MedidaAncho = MedidaAncho;
    }

    public Double getMedidaLargo() {
        return MedidaLargo;
    }

    public void setMedidaLargo(Double MedidaLargo) {
        this.MedidaLargo = MedidaLargo;
    }

    public Double getMontoCostoPromedio() {
        return MontoCostoPromedio;
    }

    public void setMontoCostoPromedio(Double MontoCostoPromedio) {
        this.MontoCostoPromedio = MontoCostoPromedio;
    }

    public double getMontoPrecio1() {
        return MontoPrecio1;
    }

    public void setMontoPrecio1(double MontoPrecio1) {
        this.MontoPrecio1 = MontoPrecio1;
    }

    public Double getMontoPrecio2() {
        return MontoPrecio2;
    }

    public void setMontoPrecio2(Double MontoPrecio2) {
        this.MontoPrecio2 = MontoPrecio2;
    }

    public Double getMontoPrecio3() {
        return MontoPrecio3;
    }

    public void setMontoPrecio3(Double MontoPrecio3) {
        this.MontoPrecio3 = MontoPrecio3;
    }

    public Double getMontoUltimoCosto() {
        return MontoUltimoCosto;
    }

    public void setMontoUltimoCosto(Double MontoUltimoCosto) {
        this.MontoUltimoCosto = MontoUltimoCosto;
    }

    public Boolean getEsActivo() {
        return esActivo;
    }

    public void setEsActivo(Boolean esActivo) {
        this.esActivo = esActivo;
    }

    public Boolean getEsCodigoAlterno() {
        return esCodigoAlterno;
    }

    public void setEsCodigoAlterno(Boolean esCodigoAlterno) {
        this.esCodigoAlterno = esCodigoAlterno;
    }

    public Boolean getEsCompuesto() {
        return esCompuesto;
    }

    public void setEsCompuesto(Boolean esCompuesto) {
        this.esCompuesto = esCompuesto;
    }

    public Boolean getEsFavorito() {
        return esFavorito;
    }

    public void setEsFavorito(Boolean esFavorito) {
        this.esFavorito = esFavorito;
    }

    public Boolean getEsGarantia() {
        return esGarantia;
    }

    public void setEsGarantia(Boolean esGarantia) {
        this.esGarantia = esGarantia;
    }

    public Boolean getEsImportado() {
        return esImportado;
    }

    public void setEsImportado(Boolean esImportado) {
        this.esImportado = esImportado;
    }

    public Boolean getEsInventario() {
        return esInventario;
    }

    public void setEsInventario(Boolean esInventario) {
        this.esInventario = esInventario;
    }

    public Boolean getEsPideComentario() {
        return esPideComentario;
    }

    public void setEsPideComentario(Boolean esPideComentario) {
        this.esPideComentario = esPideComentario;
    }

    public Boolean getEsPidePeso() {
        return esPidePeso;
    }

    public void setEsPidePeso(Boolean esPidePeso) {
        this.esPidePeso = esPidePeso;
    }

    public Boolean getEsPidePrecio() {
        return esPidePrecio;
    }

    public void setEsPidePrecio(Boolean esPidePrecio) {
        this.esPidePrecio = esPidePrecio;
    }

    public Boolean getEsPideTipoProducto() {
        return esPideTipoProducto;
    }

    public void setEsPideTipoProducto(Boolean esPideTipoProducto) {
        this.esPideTipoProducto = esPideTipoProducto;
    }

    public Boolean getEsUsoInterno() {
        return esUsoInterno;
    }

    public void setEsUsoInterno(Boolean esUsoInterno) {
        this.esUsoInterno = esUsoInterno;
    }

    public int getId_familiaProducto() {
        return id_familiaProducto;
    }

    public void setId_familiaProducto(int id_familiaProducto) {
        this.id_familiaProducto = id_familiaProducto;
    }

    public Integer getId_Marca() {
        return id_Marca;
    }

    public void setId_Marca(Integer id_Marca) {
        this.id_Marca = id_Marca;
    }

    public Integer getId_Impuesto() {
        return id_Impuesto;
    }

    public void setId_Impuesto(Integer id_Impuesto) {
        this.id_Impuesto = id_Impuesto;
    }

    public Integer getId_unidadMedida() {
        return id_unidadMedida;
    }

    public void setId_unidadMedida(Integer id_unidadMedida) {
        this.id_unidadMedida = id_unidadMedida;
    }

    public java.util.Date getFechaCreacion() {
        return FechaCreacion;
    }

    public void setFechaCreacion(java.util.Date FechaCreacion) {
        this.FechaCreacion = FechaCreacion;
    }

    public java.util.Date getFechaUltimaCompra() {
        return FechaUltimaCompra;
    }

    public void setFechaUltimaCompra(java.util.Date FechaUltimaCompra) {
        this.FechaUltimaCompra = FechaUltimaCompra;
    }

    public java.util.Date getFechaUltimaModificacion() {
        return FechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(java.util.Date FechaUltimaModificacion) {
        this.FechaUltimaModificacion = FechaUltimaModificacion;
    }

    public java.util.Date getFechaUltimaVenta() {
        return FechaUltimaVenta;
    }

    public void setFechaUltimaVenta(java.util.Date FechaUltimaVenta) {
        this.FechaUltimaVenta = FechaUltimaVenta;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
