package com.kss.kssmarketv10.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kss.kssmarketv10.db.Productos;
import com.kss.kssmarketv10.db.Clientes;
import com.kss.kssmarketv10.db.Empresa;
import com.kss.kssmarketv10.db.Productos_Familia;
import com.kss.kssmarketv10.db.Licencias;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productosDaoConfig;
    private final DaoConfig clientesDaoConfig;
    private final DaoConfig empresaDaoConfig;
    private final DaoConfig productos_FamiliaDaoConfig;
    private final DaoConfig licenciasDaoConfig;

    private final ProductosDao productosDao;
    private final ClientesDao clientesDao;
    private final EmpresaDao empresaDao;
    private final Productos_FamiliaDao productos_FamiliaDao;
    private final LicenciasDao licenciasDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productosDaoConfig = daoConfigMap.get(ProductosDao.class).clone();
        productosDaoConfig.initIdentityScope(type);

        clientesDaoConfig = daoConfigMap.get(ClientesDao.class).clone();
        clientesDaoConfig.initIdentityScope(type);

        empresaDaoConfig = daoConfigMap.get(EmpresaDao.class).clone();
        empresaDaoConfig.initIdentityScope(type);

        productos_FamiliaDaoConfig = daoConfigMap.get(Productos_FamiliaDao.class).clone();
        productos_FamiliaDaoConfig.initIdentityScope(type);

        licenciasDaoConfig = daoConfigMap.get(LicenciasDao.class).clone();
        licenciasDaoConfig.initIdentityScope(type);

        productosDao = new ProductosDao(productosDaoConfig, this);
        clientesDao = new ClientesDao(clientesDaoConfig, this);
        empresaDao = new EmpresaDao(empresaDaoConfig, this);
        productos_FamiliaDao = new Productos_FamiliaDao(productos_FamiliaDaoConfig, this);
        licenciasDao = new LicenciasDao(licenciasDaoConfig, this);

        registerDao(Productos.class, productosDao);
        registerDao(Clientes.class, clientesDao);
        registerDao(Empresa.class, empresaDao);
        registerDao(Productos_Familia.class, productos_FamiliaDao);
        registerDao(Licencias.class, licenciasDao);
    }
    
    public void clear() {
        productosDaoConfig.getIdentityScope().clear();
        clientesDaoConfig.getIdentityScope().clear();
        empresaDaoConfig.getIdentityScope().clear();
        productos_FamiliaDaoConfig.getIdentityScope().clear();
        licenciasDaoConfig.getIdentityScope().clear();
    }

    public ProductosDao getProductosDao() {
        return productosDao;
    }

    public ClientesDao getClientesDao() {
        return clientesDao;
    }

    public EmpresaDao getEmpresaDao() {
        return empresaDao;
    }

    public Productos_FamiliaDao getProductos_FamiliaDao() {
        return productos_FamiliaDao;
    }

    public LicenciasDao getLicenciasDao() {
        return licenciasDao;
    }

}
